### ISSUE TITLE
Add Flutter E2E & Integration Test

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart#2345]
### Description

```[tasklist]
### Tasks
- [x] re-enable e2e tests
- [x] valid envelope test
- [ ] invalid/corrupt envelope test
- [ ] check that a replay was captured (see RN e2e tests for API endpoints to check)
- [ ] symbolication & source context
```

**Comment by buenaflor** [comment]
For symbolication & source context e2e test we could use maestro. I dont think the flutter's integration test will be able to test that<br><br>We could at the very least test it for android, not sure about macos and ios though, I dont think you can build an obfuscated build for the simulator
